spring.application.name=SpringBootAop1


# Root Logger Level
logging.level.root=INFO

# Package Logger Level
logging.level.com.company=INFO

# Console Log Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# File Log Pattern
logging.pattern.file=%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n

# Log File Name
logging.file.name=logs/application.log