spring.application.name=JavaMailingApp

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=ayushpal13579@gmail.com
spring.mail.password=lpsp wxdk ktqu vwhh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8888