spring.application.name=LmsApplication

spring.datasource.url=jdbc:h2:file:./data/lmsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

server.port=8086
spring.thymeleaf.check-template-location=false


#openai.api.key=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